name: Verathread Web SDK

#/////////////////////////////////////////////////////////////////////////////////////////////////////////
# VERATHREAD FRONT END SDK
#/////////////////////////////////////////////////////////////////////////////////////////////////////////

on:
  pull_request:
    branches: [ 'main' ]
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_REGION: eu-west-2
  FORCE_COLOR: 1
  DRY_RUN: false
  DEPLOY: true
  RUNNER_ALLOW_RUNASROOT: "1"

jobs:
  #/////////////////////////////////////////////////////////////////////////////////////////////////////////
  # DEV
  # Flags used in other steps
  #/////////////////////////////////////////////////////////////////////////////////////////////////////////

  test:
    runs-on: ubuntu-latest
    name: "Test"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

  publish-qa-docs:
    runs-on: custom-ubuntu-20.04-4core
    name: "Build & Publish QA Docs"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Configure Environment"
        uses: ./.github/actions/configuration
        id: configure
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws-region: ${{ env.AWS_REGION }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          use-sudo: true
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 'v22.4.0'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
        env:
          FORCE_COLOR: 0
      - name: "GHCR Login"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Install"
        run: yarn install --prefer-offline --frozen-lockfile --non-interactive
      - name: "Build SCSS"
        run: yarn build:sass
      - name: "Build Docs"
        run: yarn docs

      - name: "Build Image"
        run: docker build --push -t ghcr.io/azarc-io/verathread-next-web-sdk-docs:${{ steps.configure.outputs.issue }}
#      - name: "Publish Docs"
#        uses: osiegmar/s3-publisher-action@v1
#        with:
#          bucket: sdk.verathread.dev
#          prefix: ${{ steps.configure.outputs.issue }}/
#          dir: ./_site
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: sdk-site
          path: _site
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: sdk-package
          path: dist

  release:
    runs-on: ubuntu-latest
    name: "Release"
    needs:
      - test
      - publish-qa-docs
    environment: production
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
#      - name: "Publish"
#        if: env.DRY_RUN == 'false'
#        run: |
#          cp ../../.npmrc .npmrc
#          yarn version --no-commit-hooks --no-git-tag-version --new-version ${{ needs.flags.outputs.version }}
#          yarn publish
